name: wh_sim
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: wh_sim

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - dbt_logs
  - dbt_packages
  - dbt_target

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['wh_sim', 'dbt_utils']
  - macro_namespace: dbt_date
    search_order: ['wh_sim', 'dbt_date']

vars:
  "dbt_date:time_zone": "Mountain Standard Time"
  metadata_database_name: wh__metadata


models:
  wh_sim:
    +materialized: table
    dw:
      +schema: dw
      +tags: [once_daily]
    utilities:
      +schema: utilities
      +tags: [once_daily]