wh_sim:
  target: dev
  outputs:
    # Using dev target tells the generate_database_name macro to suffix with _dev
    dev: &conn_info
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      server: "{{ env_var('DBT_FABRIC_SERVER_DEV') }}"
      database: wh__data_warehouse
      schema: dbo
      authentication: ServicePrincipal
      tenant_id: "{{ env_var('DBT_FABRIC_TENANT_ID') }}"
      client_id: "{{ env_var('DBT_FABRIC_CLIENT_ID') }}"
      client_secret: "{{ env_var('DBT_ENV_SECRET_FABRIC_CLIENT_SECRET') }}"
      threads: 8